import Head from 'next/head'
import Link from 'next/link'
import React, {useEffect, useState} from 'react'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'


// SSR option

export async function getServerSideProps(){
    const resp = await fetch('https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json')
  //  return results

  return {
    props: {
      pokemon: await resp.json()
    }
  }
  

}


export default function Home({pokemon}) {
  // const [pokemon, setPokemon] = useState([])

  // useEffect(() => {
  //   async function getPokemon(){
  //     const resp = await fetch('https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json')
  //     setPokemon(await resp.json())
  //   //  return results
  //   }
  //   getPokemon()
   
  // }, [])
  
  return (
    <div className={styles.container}>
      <Head>
        <title>My Noor Pokemon List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <div className={styles.grid}>

      {/* {JSON.stringify(pokemon)} */}
      {pokemon.map((pokemon)=>(
        <div key={pokemon.id} className={styles.card}>
          <Link href={`/pokemon/${pokemon.id}`}>
            <a>
              <img src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${pokemon?.image}`} alt={pokemon.name} />
              <h3>{pokemon.name}</h3>
             </a>
           </Link>
        </div>
      ))}  
     </div>
     </div>
  )
}
